# Generated by Django 3.0.5 on 2020-04-12 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_a', models.CharField(max_length=256)),
                ('method_b', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_speaker', models.CharField(max_length=256)),
                ('tgt_speaker', models.CharField(max_length=256)),
                ('utterance', models.CharField(max_length=256)),
                ('is_inverted', models.BooleanField(default=False)),
                ('is_former_better', models.NullBooleanField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Task')),
            ],
        ),
    ]
